using DelimitedFiles

## give a string path to the raw mapfile input generated by XSim
function process_map(rawmapfile)
    mapfile = readdlm(rawmapfile)
    m = mapfile;
    new_map = Array{Any}(undef, 3001);

    for i in 1:3001
        if i == 1
            new_map[i] = ""
            for j in 1:4
                if j >= 2
                    new_map[i] *= ","
                    new_map[i] *= m[i, j]
            
                else
                    new_map[i] *= m[i, j]
                end
            end
        else
            new_map[i] = ""
            for j in 1:4
                if j >= 2
                    new_map[i] *= ","
                    m[i, j] = string(m[i, j])
                    new_map[i] *= m[i, j]
                else
                    m[i, j] = string(m[i, j])
                    new_map[i] *= m[i, j]
                end
            end
        end
    end
    
    return new_map
end
